// Generated by gencpp from file data_collection/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DATA_COLLECTION_MESSAGE_ADDTWOINTS_H
#define DATA_COLLECTION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <data_collection/AddTwoIntsRequest.h>
#include <data_collection/AddTwoIntsResponse.h>


namespace data_collection
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace data_collection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_collection::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::data_collection::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::data_collection::AddTwoInts > {
  static const char* value()
  {
    return "data_collection/AddTwoInts";
  }

  static const char* value(const ::data_collection::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::data_collection::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::data_collection::AddTwoInts > 
template<>
struct MD5Sum< ::data_collection::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_collection::AddTwoInts >::value();
  }
  static const char* value(const ::data_collection::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_collection::AddTwoIntsRequest> should match 
// service_traits::DataType< ::data_collection::AddTwoInts > 
template<>
struct DataType< ::data_collection::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::data_collection::AddTwoInts >::value();
  }
  static const char* value(const ::data_collection::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_collection::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::data_collection::AddTwoInts > 
template<>
struct MD5Sum< ::data_collection::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_collection::AddTwoInts >::value();
  }
  static const char* value(const ::data_collection::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_collection::AddTwoIntsResponse> should match 
// service_traits::DataType< ::data_collection::AddTwoInts > 
template<>
struct DataType< ::data_collection::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::data_collection::AddTwoInts >::value();
  }
  static const char* value(const ::data_collection::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_COLLECTION_MESSAGE_ADDTWOINTS_H
