// Generated by gencpp from file data_collection/Service.msg
// DO NOT EDIT!


#ifndef DATA_COLLECTION_MESSAGE_SERVICE_H
#define DATA_COLLECTION_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <data_collection/ServiceRequest.h>
#include <data_collection/ServiceResponse.h>


namespace data_collection
{

struct Service
{

typedef ServiceRequest Request;
typedef ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service
} // namespace data_collection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_collection::Service > {
  static const char* value()
  {
    return "57d3c40ec3ac3754af76a83e6e73127a";
  }

  static const char* value(const ::data_collection::Service&) { return value(); }
};

template<>
struct DataType< ::data_collection::Service > {
  static const char* value()
  {
    return "data_collection/Service";
  }

  static const char* value(const ::data_collection::Service&) { return value(); }
};


// service_traits::MD5Sum< ::data_collection::ServiceRequest> should match 
// service_traits::MD5Sum< ::data_collection::Service > 
template<>
struct MD5Sum< ::data_collection::ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_collection::Service >::value();
  }
  static const char* value(const ::data_collection::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_collection::ServiceRequest> should match 
// service_traits::DataType< ::data_collection::Service > 
template<>
struct DataType< ::data_collection::ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::data_collection::Service >::value();
  }
  static const char* value(const ::data_collection::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_collection::ServiceResponse> should match 
// service_traits::MD5Sum< ::data_collection::Service > 
template<>
struct MD5Sum< ::data_collection::ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_collection::Service >::value();
  }
  static const char* value(const ::data_collection::ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_collection::ServiceResponse> should match 
// service_traits::DataType< ::data_collection::Service > 
template<>
struct DataType< ::data_collection::ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::data_collection::Service >::value();
  }
  static const char* value(const ::data_collection::ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_COLLECTION_MESSAGE_SERVICE_H
